//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conectai.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Conectai.Properties.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desenvolvido por Bruno Ponte.
        /// </summary>
        public static string DESENVOLVIDO_POR {
            get {
                return ResourceManager.GetString("DESENVOLVIDO_POR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O ano informado é inválido..
        /// </summary>
        public static string ERR_ANO_INVALIDO {
            get {
                return ResourceManager.GetString("ERR_ANO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar o ano e o mês..
        /// </summary>
        public static string ERR_ANO_MES_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_ANO_MES_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar o ano..
        /// </summary>
        public static string ERR_ANO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_ANO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arquivo não existe..
        /// </summary>
        public static string ERR_ARQUIVO_NAO_EXISTE {
            get {
                return ResourceManager.GetString("ERR_ARQUIVO_NAO_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível avaliar o atendimento..
        /// </summary>
        public static string ERR_ATENDIMENTO_AVALIADO {
            get {
                return ResourceManager.GetString("ERR_ATENDIMENTO_AVALIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível excluir o ativo..
        /// </summary>
        public static string ERR_ATIVO_EXCLUIR {
            get {
                return ResourceManager.GetString("ERR_ATIVO_EXCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ativo não encontrado..
        /// </summary>
        public static string ERR_ATIVO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERR_ATIVO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar o ativo..
        /// </summary>
        public static string ERR_ATIVO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_ATIVO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário selecionar o arquivo para download..
        /// </summary>
        public static string ERR_CAMPO_NOME_ARQ_DOWNLOAD_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_CAMPO_NOME_ARQ_DOWNLOAD_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor informado no campo &apos;{0}&apos;  deve ser diferente de zero..
        /// </summary>
        public static string ERR_CAMPO_VALOR_DECIMAL_DEVE_SER_DIFERENTE_ZERO {
            get {
                return ResourceManager.GetString("ERR_CAMPO_VALOR_DECIMAL_DEVE_SER_DIFERENTE_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor informado no campo &apos;{0}&apos;  deve ser maior ou igual a zero..
        /// </summary>
        public static string ERR_CAMPO_VALOR_DECIMAL_DEVE_SER_MAIOR_IGUAL_ZERO {
            get {
                return ResourceManager.GetString("ERR_CAMPO_VALOR_DECIMAL_DEVE_SER_MAIOR_IGUAL_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor informado no campo &apos;{0}&apos;  deve ser maior que zero..
        /// </summary>
        public static string ERR_CAMPO_VALOR_DECIMAL_DEVE_SER_MAIOR_QUE_ZERO {
            get {
                return ResourceManager.GetString("ERR_CAMPO_VALOR_DECIMAL_DEVE_SER_MAIOR_QUE_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor informado no campo &apos;{0}&apos; é inválido. Favor informar um número com até {1} casas decimais e separador decimal utilizando vírgula..
        /// </summary>
        public static string ERR_CAMPO_VALOR_DECIMAL_INVALIDO {
            get {
                return ResourceManager.GetString("ERR_CAMPO_VALOR_DECIMAL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &apos;{0}&apos; é obrigatório..
        /// </summary>
        public static string ERR_CAMPO_VALOR_DECIMAL_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_CAMPO_VALOR_DECIMAL_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar o código..
        /// </summary>
        public static string ERR_CODIGO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_CODIGO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código informado é inválido..
        /// </summary>
        public static string ERR_CODIGO_TAMANHO_INVALIDO {
            get {
                return ResourceManager.GetString("ERR_CODIGO_TAMANHO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a String de conexão &apos;{0}&apos; com o Banco de Dados não localizada..
        /// </summary>
        public static string ERR_CONN_STRING_VAZIA {
            get {
                return ResourceManager.GetString("ERR_CONN_STRING_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar o CPF..
        /// </summary>
        public static string ERR_CPF_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_CPF_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar a data de aquisição..
        /// </summary>
        public static string ERR_DATA_AQUISICAO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_DATA_AQUISICAO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível assumir a demanda..
        /// </summary>
        public static string ERR_DEMANDA_ASSUMIR {
            get {
                return ResourceManager.GetString("ERR_DEMANDA_ASSUMIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível excluir a demanda..
        /// </summary>
        public static string ERR_DEMANDA_EXCLUIR {
            get {
                return ResourceManager.GetString("ERR_DEMANDA_EXCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível finalizar a demanda..
        /// </summary>
        public static string ERR_DEMANDA_FINALIZAR {
            get {
                return ResourceManager.GetString("ERR_DEMANDA_FINALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Demanda não encontrada..
        /// </summary>
        public static string ERR_DEMANDA_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("ERR_DEMANDA_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar a descrição..
        /// </summary>
        public static string ERR_DESCRICAO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_DESCRICAO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descrição informada é inválida..
        /// </summary>
        public static string ERR_DESCRICAO_TAMANHO_INVALIDO {
            get {
                return ResourceManager.GetString("ERR_DESCRICAO_TAMANHO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar o e-mail..
        /// </summary>
        public static string ERR_EMAIL_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_EMAIL_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail informado é inválido..
        /// </summary>
        public static string ERR_EMAIL_TAMANHO_INVALIDO {
            get {
                return ResourceManager.GetString("ERR_EMAIL_TAMANHO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível excluir o espaço público..
        /// </summary>
        public static string ERR_ESPACO_PUBLICO_EXCLUIR {
            get {
                return ResourceManager.GetString("ERR_ESPACO_PUBLICO_EXCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Espaço Público não encontrado..
        /// </summary>
        public static string ERR_ESPACO_PUBLICO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERR_ESPACO_PUBLICO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível excluir o imposto do usuário..
        /// </summary>
        public static string ERR_IMPOSTO_USUARIO_EXCLUIR {
            get {
                return ResourceManager.GetString("ERR_IMPOSTO_USUARIO_EXCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Imposto do usuário não encontrado..
        /// </summary>
        public static string ERR_IMPOSTO_USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERR_IMPOSTO_USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar a senha do usuário..
        /// </summary>
        public static string ERR_LOGIN_CAMPO_SENHA_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_LOGIN_CAMPO_SENHA_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar o usuário..
        /// </summary>
        public static string ERR_LOGIN_CAMPO_USUARIO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_LOGIN_CAMPO_USUARIO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O login do usuário deve ter no máximo 8 caracteres..
        /// </summary>
        public static string ERR_LOGIN_CAMPO_USUARIO_TAMANHO_INVALIDO {
            get {
                return ResourceManager.GetString("ERR_LOGIN_CAMPO_USUARIO_TAMANHO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O mês selecionado é inválido..
        /// </summary>
        public static string ERR_MES_INVALIDO {
            get {
                return ResourceManager.GetString("ERR_MES_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar o mês..
        /// </summary>
        public static string ERR_MES_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_MES_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arquivo selecionado para download não encontrado..
        /// </summary>
        public static string ERR_NOME_ARQ_DOWNLOAD_INVALIDO {
            get {
                return ResourceManager.GetString("ERR_NOME_ARQ_DOWNLOAD_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar o nome..
        /// </summary>
        public static string ERR_NOME_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_NOME_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome informado é inválido..
        /// </summary>
        public static string ERR_NOME_TAMANHO_INVALIDO {
            get {
                return ResourceManager.GetString("ERR_NOME_TAMANHO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar a observação.
        /// </summary>
        public static string ERR_OBSERVACAO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_OBSERVACAO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A observação informada é inválida..
        /// </summary>
        public static string ERR_OBSERVACAO_TAMANHO_INVALIDO {
            get {
                return ResourceManager.GetString("ERR_OBSERVACAO_TAMANHO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário selecionar o perfil..
        /// </summary>
        public static string ERR_PERFIL_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_PERFIL_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário selecionar o perfil de risco..
        /// </summary>
        public static string ERR_PERFIL_RISCO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_PERFIL_RISCO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar o preço médio..
        /// </summary>
        public static string ERR_PRECO_MEDIO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_PRECO_MEDIO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar a quantidade de cotas..
        /// </summary>
        public static string ERR_QTDE_COTAS_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_QTDE_COTAS_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A quantidade de linhas excede o máximo permitido para o relatório..
        /// </summary>
        public static string ERR_RELATORIO_QUANTIDADE_LINHAS_EXCEDE_MAX_PERMITIDO {
            get {
                return ResourceManager.GetString("ERR_RELATORIO_QUANTIDADE_LINHAS_EXCEDE_MAX_PERMITIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foram encontrados dados para o filtro selecionado para o relatório..
        /// </summary>
        public static string ERR_RELATORIO_SEM_DADOS {
            get {
                return ResourceManager.GetString("ERR_RELATORIO_SEM_DADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível excluir o rendimento..
        /// </summary>
        public static string ERR_RENDIMENTO_EXCLUIR {
            get {
                return ResourceManager.GetString("ERR_RENDIMENTO_EXCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rendimento não encontrado..
        /// </summary>
        public static string ERR_RENDIMENTO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERR_RENDIMENTO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar o saldo atual..
        /// </summary>
        public static string ERR_SALDO_ATUAL_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_SALDO_ATUAL_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma string de conexão com o Banco de Dados localizada..
        /// </summary>
        public static string ERR_SEM_CONN_STRING {
            get {
                return ResourceManager.GetString("ERR_SEM_CONN_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar a senha..
        /// </summary>
        public static string ERR_SENHA_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_SENHA_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha informada é inválida..
        /// </summary>
        public static string ERR_SENHA_TAMANHO_INVALIDO {
            get {
                return ResourceManager.GetString("ERR_SENHA_TAMANHO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não tem acesso a este menu.&lt;br/&gt;
        ///Faça o login para obter acesso. .
        /// </summary>
        public static string ERR_SESSAO_EXPIRADA {
            get {
                return ResourceManager.GetString("ERR_SESSAO_EXPIRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua sessão expirou.&lt;br /&gt;
        ///Para voltar a utilizar o sistema, &lt;a href=&apos;{0}&apos; class=&apos;a-link-clique-aqui&apos;&gt;clique aqui&lt;/a&gt;..
        /// </summary>
        public static string ERR_SESSAO_EXPIRADA_AJAX {
            get {
                return ResourceManager.GetString("ERR_SESSAO_EXPIRADA_AJAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar a sigla..
        /// </summary>
        public static string ERR_SIGLA_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_SIGLA_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A sigla informada é inválida..
        /// </summary>
        public static string ERR_SIGLA_TAMANHO_INVALIDO {
            get {
                return ResourceManager.GetString("ERR_SIGLA_TAMANHO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro inesperado ao validar as informações..
        /// </summary>
        public static string ERR_SQL_NAO_TRATADO {
            get {
                return ResourceManager.GetString("ERR_SQL_NAO_TRATADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível excluir o imposto.
        /// </summary>
        public static string ERR_TIPO_IMPOSTO_EXCLUIR {
            get {
                return ResourceManager.GetString("ERR_TIPO_IMPOSTO_EXCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de imposto não encontrado..
        /// </summary>
        public static string ERR_TIPO_IMPOSTO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERR_TIPO_IMPOSTO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível excluir o tipo de investimento..
        /// </summary>
        public static string ERR_TIPO_INVESTIMENTO_EXCLUIR {
            get {
                return ResourceManager.GetString("ERR_TIPO_INVESTIMENTO_EXCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de investimento não encontrado..
        /// </summary>
        public static string ERR_TIPO_INVESTIMENTO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERR_TIPO_INVESTIMENTO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário selecionar o tipo de investimento..
        /// </summary>
        public static string ERR_TIPO_INVESTIMENTO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_TIPO_INVESTIMENTO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar o tipo de serviço.
        /// </summary>
        public static string ERR_TIPO_SERVICO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_TIPO_SERVICO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível excluir o usuário..
        /// </summary>
        public static string ERR_USUARIO_EXCLUIR {
            get {
                return ResourceManager.GetString("ERR_USUARIO_EXCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário inválido ou não associado ao sistema..
        /// </summary>
        public static string ERR_USUARIO_INVALIDO_OU_NAO_ASSOCIADO {
            get {
                return ResourceManager.GetString("ERR_USUARIO_INVALIDO_OU_NAO_ASSOCIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado..
        /// </summary>
        public static string ERR_USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERR_USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha inválida..
        /// </summary>
        public static string ERR_USUARIO_SENHA_INVALIDA {
            get {
                return ResourceManager.GetString("ERR_USUARIO_SENHA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar o valor do imposto..
        /// </summary>
        public static string ERR_VALOR_IMPOSTO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_VALOR_IMPOSTO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar o valor investido..
        /// </summary>
        public static string ERR_VALOR_INVESTIDO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ERR_VALOR_INVESTIDO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro imprimindo a adevertência/suspensão.  A impressão retornou um arquivo com 0 bytes ou o content type vazio..
        /// </summary>
        public static string ERRO_IMPRIMIR_CONTEUDO_INVALIDO {
            get {
                return ResourceManager.GetString("ERRO_IMPRIMIR_CONTEUDO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O download não poderá ser realizado.&lt;br/&gt;
        ///Ocorreu um erro preparando o arquivo para download..
        /// </summary>
        public static string ERRO_PREPARANDO_ARQ_DOWNLOAD {
            get {
                return ResourceManager.GetString("ERRO_PREPARANDO_ARQ_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p&gt;Ocorreu um erro inesperado.&lt;/p&gt;
        ///&lt;p&gt;O fato de você estar vendo essa mensagem significa que automaticamente fomos notificados deste problema.&lt;/p&gt;
        ///&lt;p&gt;Se o problema persistir, por favor aguarde mais um momento para tentar novamente.&lt;/p&gt;.
        /// </summary>
        public static string EXCEPTION_MSG_ERRO {
            get {
                return ResourceManager.GetString("EXCEPTION_MSG_ERRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Obrigado pela sua avaliação!.
        /// </summary>
        public static string MSG_ATENDIMENTO_AVALIADO_SUCESSO {
            get {
                return ResourceManager.GetString("MSG_ATENDIMENTO_AVALIADO_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rendimentos gerados com sucesso..
        /// </summary>
        public static string MSG_RENDIMENTO_GERADO_SUCESSO {
            get {
                return ResourceManager.GetString("MSG_RENDIMENTO_GERADO_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ação.
        /// </summary>
        public static string STR_ACAO {
            get {
                return ResourceManager.GetString("STR_ACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ações.
        /// </summary>
        public static string STR_ACOES {
            get {
                return ResourceManager.GetString("STR_ACOES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agressivo.
        /// </summary>
        public static string STR_AGRESSIVO {
            get {
                return ResourceManager.GetString("STR_AGRESSIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alocação Atual de Recursos.
        /// </summary>
        public static string STR_ALOCACAO_ATUAL_RECURSOS {
            get {
                return ResourceManager.GetString("STR_ALOCACAO_ATUAL_RECURSOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alocação Indicada.
        /// </summary>
        public static string STR_ALOCACAO_INDICADA {
            get {
                return ResourceManager.GetString("STR_ALOCACAO_INDICADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alocações por Perfil.
        /// </summary>
        public static string STR_ALOCACOES_PERFIL {
            get {
                return ResourceManager.GetString("STR_ALOCACOES_PERFIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterar Espaço Público.
        /// </summary>
        public static string STR_ALTERAR_ESPACO_PUBLICO {
            get {
                return ResourceManager.GetString("STR_ALTERAR_ESPACO_PUBLICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ano.
        /// </summary>
        public static string STR_ANO {
            get {
                return ResourceManager.GetString("STR_ANO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ativo.
        /// </summary>
        public static string STR_ATIVO {
            get {
                return ResourceManager.GetString("STR_ATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ativos.
        /// </summary>
        public static string STR_ATIVOS {
            get {
                return ResourceManager.GetString("STR_ATIVOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atual.
        /// </summary>
        public static string STR_ATUAL {
            get {
                return ResourceManager.GetString("STR_ATUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atual R$.
        /// </summary>
        public static string STR_ATUAL_RS {
            get {
                return ResourceManager.GetString("STR_ATUAL_RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Avaliar Atendimento.
        /// </summary>
        public static string STR_AVALIAR_ATENDIMENTO {
            get {
                return ResourceManager.GetString("STR_AVALIAR_ATENDIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Ativos.
        /// </summary>
        public static string STR_CADASTRO_ATIVOS {
            get {
                return ResourceManager.GetString("STR_CADASTRO_ATIVOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastros.
        /// </summary>
        public static string STR_CADASTROS {
            get {
                return ResourceManager.GetString("STR_CADASTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Chamados.
        /// </summary>
        public static string STR_CHAMADOS {
            get {
                return ResourceManager.GetString("STR_CHAMADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Chamados em Aberto.
        /// </summary>
        public static string STR_CHAMADOS_EM_ABERTO {
            get {
                return ResourceManager.GetString("STR_CHAMADOS_EM_ABERTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Chat com a Central de Atendimento.
        /// </summary>
        public static string STR_CHAT_CENTRAL_ATENDIMENTO {
            get {
                return ResourceManager.GetString("STR_CHAT_CENTRAL_ATENDIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidadão.
        /// </summary>
        public static string STR_CIDADAO {
            get {
                return ResourceManager.GetString("STR_CIDADAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código.
        /// </summary>
        public static string STR_CODIGO {
            get {
                return ResourceManager.GetString("STR_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código do Ativo.
        /// </summary>
        public static string STR_CODIGO_ATIVO {
            get {
                return ResourceManager.GetString("STR_CODIGO_ATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Comparativo Mensal - Investimento Acumulado x Saldo.
        /// </summary>
        public static string STR_COMPARATIVO_MENSAL {
            get {
                return ResourceManager.GetString("STR_COMPARATIVO_MENSAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conservador.
        /// </summary>
        public static string STR_CONSERVADOR {
            get {
                return ResourceManager.GetString("STR_CONSERVADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Consultar e emitir segunda via de impostos.
        /// </summary>
        public static string STR_CONSULTAR_EMITIR_SEGUNDA_VIA_IMPOSTOS {
            get {
                return ResourceManager.GetString("STR_CONSULTAR_EMITIR_SEGUNDA_VIA_IMPOSTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Consultar Gestão dos Atendimentos.
        /// </summary>
        public static string STR_CONSULTAR_GESTAO_ATENDIMENTO {
            get {
                return ResourceManager.GetString("STR_CONSULTAR_GESTAO_ATENDIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cotação.
        /// </summary>
        public static string STR_COTACAO {
            get {
                return ResourceManager.GetString("STR_COTACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cotas.
        /// </summary>
        public static string STR_COTAS {
            get {
                return ResourceManager.GetString("STR_COTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        public static string STR_CPF {
            get {
                return ResourceManager.GetString("STR_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Abertura.
        /// </summary>
        public static string STR_DATA_ABERTURA {
            get {
                return ResourceManager.GetString("STR_DATA_ABERTURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Aquisição.
        /// </summary>
        public static string STR_DATA_AQUISICAO {
            get {
                return ResourceManager.GetString("STR_DATA_AQUISICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Encerramento.
        /// </summary>
        public static string STR_DATA_ENCERRAMENTO {
            get {
                return ResourceManager.GetString("STR_DATA_ENCERRAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Limite.
        /// </summary>
        public static string STR_DATA_LIMITE {
            get {
                return ResourceManager.GetString("STR_DATA_LIMITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Consultar Demanda.
        /// </summary>
        public static string STR_DEMANDA_CONSULTAR {
            get {
                return ResourceManager.GetString("STR_DEMANDA_CONSULTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Criar Demanda.
        /// </summary>
        public static string STR_DEMANDA_CRIAR {
            get {
                return ResourceManager.GetString("STR_DEMANDA_CRIAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Encerrar Demanda.
        /// </summary>
        public static string STR_DEMANDA_ENCERRAR {
            get {
                return ResourceManager.GetString("STR_DEMANDA_ENCERRAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Demandas no Mapa do Município.
        /// </summary>
        public static string STR_DEMANDA_MAPA_MUNICIPIO {
            get {
                return ResourceManager.GetString("STR_DEMANDA_MAPA_MUNICIPIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        public static string STR_DESCRICAO {
            get {
                return ResourceManager.GetString("STR_DESCRICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição do Ativo.
        /// </summary>
        public static string STR_DESCRICAO_ATIVO {
            get {
                return ResourceManager.GetString("STR_DESCRICAO_ATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição do Grupo.
        /// </summary>
        public static string STR_DESCRICAO_GRUPO {
            get {
                return ResourceManager.GetString("STR_DESCRICAO_GRUPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição do Tipo.
        /// </summary>
        public static string STR_DESCRICAO_TIPO {
            get {
                return ResourceManager.GetString("STR_DESCRICAO_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Detalhamento.
        /// </summary>
        public static string STR_DETALHAMENTO {
            get {
                return ResourceManager.GetString("STR_DETALHAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Alocação de Perfil.
        /// </summary>
        public static string STR_EDITAR_ALOCACAO_PERFIL {
            get {
                return ResourceManager.GetString("STR_EDITAR_ALOCACAO_PERFIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Ativo de Investimento.
        /// </summary>
        public static string STR_EDITAR_ATIVO_INVESTIMENTO {
            get {
                return ResourceManager.GetString("STR_EDITAR_ATIVO_INVESTIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterar Demanda.
        /// </summary>
        public static string STR_EDITAR_DEMANDA {
            get {
                return ResourceManager.GetString("STR_EDITAR_DEMANDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Grupo de Investimento.
        /// </summary>
        public static string STR_EDITAR_GRUPO_INVESTIMENTO {
            get {
                return ResourceManager.GetString("STR_EDITAR_GRUPO_INVESTIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Imposto do Usuário.
        /// </summary>
        public static string STR_EDITAR_IMPOSTO_USUARIO {
            get {
                return ResourceManager.GetString("STR_EDITAR_IMPOSTO_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Rendimento.
        /// </summary>
        public static string STR_EDITAR_RENDIMENTO {
            get {
                return ResourceManager.GetString("STR_EDITAR_RENDIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterar Tipo de Imposto.
        /// </summary>
        public static string STR_EDITAR_TIPO_IMPOSTO {
            get {
                return ResourceManager.GetString("STR_EDITAR_TIPO_IMPOSTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Tipo de Investimento.
        /// </summary>
        public static string STR_EDITAR_TIPO_INVESTIMENTO {
            get {
                return ResourceManager.GetString("STR_EDITAR_TIPO_INVESTIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail.
        /// </summary>
        public static string STR_EMAIL {
            get {
                return ResourceManager.GetString("STR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Equipe de Campo.
        /// </summary>
        public static string STR_EQUIPE_CAMPO {
            get {
                return ResourceManager.GetString("STR_EQUIPE_CAMPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Espaço Público.
        /// </summary>
        public static string STR_ESPACO_PUBLICO {
            get {
                return ResourceManager.GetString("STR_ESPACO_PUBLICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Será gerado o próximo mês, copiando as informações do último período.&lt;br /&gt;Os valores também serão copiados para o próximo mês..
        /// </summary>
        public static string STR_GERA_PERIODO_INFORMATIVO {
            get {
                return ResourceManager.GetString("STR_GERA_PERIODO_INFORMATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerenciar Guia de Espaço Público.
        /// </summary>
        public static string STR_GERENCIAR_GUIA_ESPACO_PUBLICO {
            get {
                return ResourceManager.GetString("STR_GERENCIAR_GUIA_ESPACO_PUBLICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerenciar Impostos por Usuário.
        /// </summary>
        public static string STR_GERENCIAR_IMPOSTOS_POR_USUARIO {
            get {
                return ResourceManager.GetString("STR_GERENCIAR_IMPOSTOS_POR_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerenciar Tipos de Impostos.
        /// </summary>
        public static string STR_GERENCIAR_TIPOS_IMPOSTOS {
            get {
                return ResourceManager.GetString("STR_GERENCIAR_TIPOS_IMPOSTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo.
        /// </summary>
        public static string STR_GRUPO {
            get {
                return ResourceManager.GetString("STR_GRUPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo do Investimento.
        /// </summary>
        public static string STR_GRUPO_INVESTIMENTO {
            get {
                return ResourceManager.GetString("STR_GRUPO_INVESTIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupos de Investimento.
        /// </summary>
        public static string STR_GRUPOS_INVESTIMENTO {
            get {
                return ResourceManager.GetString("STR_GRUPOS_INVESTIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IBOVESPA.
        /// </summary>
        public static string STR_IBOVESPA {
            get {
                return ResourceManager.GetString("STR_IBOVESPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Imposto.
        /// </summary>
        public static string STR_IMPOSTO {
            get {
                return ResourceManager.GetString("STR_IMPOSTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Imposto de Renda.
        /// </summary>
        public static string STR_IMPOSTO_RENDA {
            get {
                return ResourceManager.GetString("STR_IMPOSTO_RENDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impostos por Usuário.
        /// </summary>
        public static string STR_IMPOSTOS_POR_USUARIO {
            get {
                return ResourceManager.GetString("STR_IMPOSTOS_POR_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir Alocação de Perfil.
        /// </summary>
        public static string STR_INCLUIR_ALOCACAO_PERFIL {
            get {
                return ResourceManager.GetString("STR_INCLUIR_ALOCACAO_PERFIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir Ativo de Investimento.
        /// </summary>
        public static string STR_INCLUIR_ATIVO_INVESTIMENTO {
            get {
                return ResourceManager.GetString("STR_INCLUIR_ATIVO_INVESTIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir Demanda.
        /// </summary>
        public static string STR_INCLUIR_DEMANDA {
            get {
                return ResourceManager.GetString("STR_INCLUIR_DEMANDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir Espaço Público.
        /// </summary>
        public static string STR_INCLUIR_ESPACO_PUBLICO {
            get {
                return ResourceManager.GetString("STR_INCLUIR_ESPACO_PUBLICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir Grupo de Investimento.
        /// </summary>
        public static string STR_INCLUIR_GRUPO_INVESTIMENTO {
            get {
                return ResourceManager.GetString("STR_INCLUIR_GRUPO_INVESTIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir Imposto do Usuário.
        /// </summary>
        public static string STR_INCLUIR_IMPOSTO_USUARIO {
            get {
                return ResourceManager.GetString("STR_INCLUIR_IMPOSTO_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir Rendimento.
        /// </summary>
        public static string STR_INCLUIR_RENDIMENTO {
            get {
                return ResourceManager.GetString("STR_INCLUIR_RENDIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir Tipo de Imposto.
        /// </summary>
        public static string STR_INCLUIR_TIPO_IMPOSTO {
            get {
                return ResourceManager.GetString("STR_INCLUIR_TIPO_IMPOSTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir Tipo de Investimento.
        /// </summary>
        public static string STR_INCLUIR_TIPO_INVESTIMENTO {
            get {
                return ResourceManager.GetString("STR_INCLUIR_TIPO_INVESTIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Indicadores do Andamento de Demandas.
        /// </summary>
        public static string STR_INDICADORES_ANDAMENTO_DEMANDAS {
            get {
                return ResourceManager.GetString("STR_INDICADORES_ANDAMENTO_DEMANDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Indicadores de Demanda.
        /// </summary>
        public static string STR_INDICADORES_DEMANDA {
            get {
                return ResourceManager.GetString("STR_INDICADORES_DEMANDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Índice de Satisfação do Cidadão.
        /// </summary>
        public static string STR_INDICE_SATISFACAO_CIDADAO {
            get {
                return ResourceManager.GetString("STR_INDICE_SATISFACAO_CIDADAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe de Rendimentos.
        /// </summary>
        public static string STR_INFORME_RENDIMENTOS {
            get {
                return ResourceManager.GetString("STR_INFORME_RENDIMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Investimento.
        /// </summary>
        public static string STR_INVESTIMENTO {
            get {
                return ResourceManager.GetString("STR_INVESTIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lucro Estimado.
        /// </summary>
        public static string STR_LUCRO_ESTIMADO {
            get {
                return ResourceManager.GetString("STR_LUCRO_ESTIMADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lucro/Prejuízo.
        /// </summary>
        public static string STR_LUCRO_PREJUIZO {
            get {
                return ResourceManager.GetString("STR_LUCRO_PREJUIZO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mês.
        /// </summary>
        public static string STR_MES {
            get {
                return ResourceManager.GetString("STR_MES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Minhas Demandas.
        /// </summary>
        public static string STR_MINHAS_DEMANDAS {
            get {
                return ResourceManager.GetString("STR_MINHAS_DEMANDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Moderado.
        /// </summary>
        public static string STR_MODERADO {
            get {
                return ResourceManager.GetString("STR_MODERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existem alocações por perfil cadastrados..
        /// </summary>
        public static string STR_NAO_EXISTEM_ALOCACOES_PERFIL_CADASTRADO {
            get {
                return ResourceManager.GetString("STR_NAO_EXISTEM_ALOCACOES_PERFIL_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existem ativos de investimento cadastrados..
        /// </summary>
        public static string STR_NAO_EXISTEM_ATIVOS_INVESTIMENTO_CADASTRADO {
            get {
                return ResourceManager.GetString("STR_NAO_EXISTEM_ATIVOS_INVESTIMENTO_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existem demandas cadastradas..
        /// </summary>
        public static string STR_NAO_EXISTEM_DEMANDAS_CADASTRADAS {
            get {
                return ResourceManager.GetString("STR_NAO_EXISTEM_DEMANDAS_CADASTRADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existem demandas para o filtro informado..
        /// </summary>
        public static string STR_NAO_EXISTEM_DEMANDAS_PARA_O_FILTRO {
            get {
                return ResourceManager.GetString("STR_NAO_EXISTEM_DEMANDAS_PARA_O_FILTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existem espaços públicos cadastrados..
        /// </summary>
        public static string STR_NAO_EXISTEM_ESPACOS_PUBLICO_CADASTRADO {
            get {
                return ResourceManager.GetString("STR_NAO_EXISTEM_ESPACOS_PUBLICO_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existem grupos de investimento cadastrados..
        /// </summary>
        public static string STR_NAO_EXISTEM_GRUPOS_INVESTIMENTO_CADASTRADO {
            get {
                return ResourceManager.GetString("STR_NAO_EXISTEM_GRUPOS_INVESTIMENTO_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existem impostos associados a usuários..
        /// </summary>
        public static string STR_NAO_EXISTEM_IMPOSTOS_PARA_USUARIO_CADASTRADO {
            get {
                return ResourceManager.GetString("STR_NAO_EXISTEM_IMPOSTOS_PARA_USUARIO_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existem rendimentos cadastrados..
        /// </summary>
        public static string STR_NAO_EXISTEM_RENDIMENTOS_CADASTRADO {
            get {
                return ResourceManager.GetString("STR_NAO_EXISTEM_RENDIMENTOS_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existem tipos de impostos cadastrados..
        /// </summary>
        public static string STR_NAO_EXISTEM_TIPOS_IMPOSTO_CADASTRADO {
            get {
                return ResourceManager.GetString("STR_NAO_EXISTEM_TIPOS_IMPOSTO_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existem tipos de investimento cadastrados..
        /// </summary>
        public static string STR_NAO_EXISTEM_TIPOS_INVESTIMENTO_CADASTRADO {
            get {
                return ResourceManager.GetString("STR_NAO_EXISTEM_TIPOS_INVESTIMENTO_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existem usuários cadastrados..
        /// </summary>
        public static string STR_NAO_EXISTEM_USUARIOS_CADASTRADO {
            get {
                return ResourceManager.GetString("STR_NAO_EXISTEM_USUARIOS_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string STR_NOME {
            get {
                return ResourceManager.GetString("STR_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do Ativo.
        /// </summary>
        public static string STR_NOME_ATIVO {
            get {
                return ResourceManager.GetString("STR_NOME_ATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nota de Avaliação.
        /// </summary>
        public static string STR_NOTA_AVALIACAO {
            get {
                return ResourceManager.GetString("STR_NOTA_AVALIACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Demanda.
        /// </summary>
        public static string STR_NUMERO_DEMANDA {
            get {
                return ResourceManager.GetString("STR_NUMERO_DEMANDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a * obrigatório.
        /// </summary>
        public static string STR_OBRIGATORIO {
            get {
                return ResourceManager.GetString("STR_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observação.
        /// </summary>
        public static string STR_OBSERVACAO {
            get {
                return ResourceManager.GetString("STR_OBSERVACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observações.
        /// </summary>
        public static string STR_OBSERVACOES {
            get {
                return ResourceManager.GetString("STR_OBSERVACOES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Órgão Municipal.
        /// </summary>
        public static string STR_ORGAO_MUNICIPAL {
            get {
                return ResourceManager.GetString("STR_ORGAO_MUNICIPAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a % Alocação.
        /// </summary>
        public static string STR_PERCENTUAL_ALOCACAO {
            get {
                return ResourceManager.GetString("STR_PERCENTUAL_ALOCACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Percentual de Alocação.
        /// </summary>
        public static string STR_PERCENTUAL_ALOCACAO_DESCRICAO {
            get {
                return ResourceManager.GetString("STR_PERCENTUAL_ALOCACAO_DESCRICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a % Crescimento.
        /// </summary>
        public static string STR_PERCENTUAL_CRESCIMENTO {
            get {
                return ResourceManager.GetString("STR_PERCENTUAL_CRESCIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perfil.
        /// </summary>
        public static string STR_PERFIL {
            get {
                return ResourceManager.GetString("STR_PERFIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perfil do Risco.
        /// </summary>
        public static string STR_PERFIL_RISCO {
            get {
                return ResourceManager.GetString("STR_PERFIL_RISCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preço Médio.
        /// </summary>
        public static string STR_PRECO_MEDIO {
            get {
                return ResourceManager.GetString("STR_PRECO_MEDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade.
        /// </summary>
        public static string STR_QUANTIDADE {
            get {
                return ResourceManager.GetString("STR_QUANTIDADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade de Cotas.
        /// </summary>
        public static string STR_QUANTIDADE_COTAS {
            get {
                return ResourceManager.GetString("STR_QUANTIDADE_COTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Relatório de Informe de Rendimentos.
        /// </summary>
        public static string STR_RELATORIO_INFORME_RENDIMENTOS {
            get {
                return ResourceManager.GetString("STR_RELATORIO_INFORME_RENDIMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Relatórios.
        /// </summary>
        public static string STR_RELATORIOS {
            get {
                return ResourceManager.GetString("STR_RELATORIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rendimentos.
        /// </summary>
        public static string STR_RENDIMENTOS {
            get {
                return ResourceManager.GetString("STR_RENDIMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saldo Atual.
        /// </summary>
        public static string STR_SALDO_ATUAL {
            get {
                return ResourceManager.GetString("STR_SALDO_ATUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione.
        /// </summary>
        public static string STR_SELECIONE {
            get {
                return ResourceManager.GetString("STR_SELECIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um ativo.
        /// </summary>
        public static string STR_SELECIONE_ATIVO {
            get {
                return ResourceManager.GetString("STR_SELECIONE_ATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um grupo de investimento.
        /// </summary>
        public static string STR_SELECIONE_GRUPO_INVESTIMENTO {
            get {
                return ResourceManager.GetString("STR_SELECIONE_GRUPO_INVESTIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um mês.
        /// </summary>
        public static string STR_SELECIONE_MES {
            get {
                return ResourceManager.GetString("STR_SELECIONE_MES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione a nota.
        /// </summary>
        public static string STR_SELECIONE_NOTA {
            get {
                return ResourceManager.GetString("STR_SELECIONE_NOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um perfil de risco.
        /// </summary>
        public static string STR_SELECIONE_PERFIL_RISCO {
            get {
                return ResourceManager.GetString("STR_SELECIONE_PERFIL_RISCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um tipo de imposto.
        /// </summary>
        public static string STR_SELECIONE_TIPO_IMPOSTO {
            get {
                return ResourceManager.GetString("STR_SELECIONE_TIPO_IMPOSTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um tipo de investimento.
        /// </summary>
        public static string STR_SELECIONE_TIPO_INVESTIMENTO {
            get {
                return ResourceManager.GetString("STR_SELECIONE_TIPO_INVESTIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione o tipo de serviço.
        /// </summary>
        public static string STR_SELECIONE_TIPO_SERVICO {
            get {
                return ResourceManager.GetString("STR_SELECIONE_TIPO_SERVICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string STR_SENHA {
            get {
                return ResourceManager.GetString("STR_SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sigla.
        /// </summary>
        public static string STR_SIGLA {
            get {
                return ResourceManager.GetString("STR_SIGLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        public static string STR_STATUS {
            get {
                return ResourceManager.GetString("STR_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status da Demanda.
        /// </summary>
        public static string STR_STATUS_DEMANDA {
            get {
                return ResourceManager.GetString("STR_STATUS_DEMANDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo.
        /// </summary>
        public static string STR_TIPO {
            get {
                return ResourceManager.GetString("STR_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de Imposto.
        /// </summary>
        public static string STR_TIPO_IMPOSTO {
            get {
                return ResourceManager.GetString("STR_TIPO_IMPOSTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de Investimento.
        /// </summary>
        public static string STR_TIPO_INVESTIMENTO {
            get {
                return ResourceManager.GetString("STR_TIPO_INVESTIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de Serviço.
        /// </summary>
        public static string STR_TIPO_SERVICO {
            get {
                return ResourceManager.GetString("STR_TIPO_SERVICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipos de Imposto.
        /// </summary>
        public static string STR_TIPOS_IMPOSTO {
            get {
                return ResourceManager.GetString("STR_TIPOS_IMPOSTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipos de Investimento.
        /// </summary>
        public static string STR_TIPOS_INVESTIMENTO {
            get {
                return ResourceManager.GetString("STR_TIPOS_INVESTIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Título.
        /// </summary>
        public static string STR_TITULO {
            get {
                return ResourceManager.GetString("STR_TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total Investido.
        /// </summary>
        public static string STR_TOTAL_INVESTIDO {
            get {
                return ResourceManager.GetString("STR_TOTAL_INVESTIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Último Período:.
        /// </summary>
        public static string STR_ULTIMO_PERIODO {
            get {
                return ResourceManager.GetString("STR_ULTIMO_PERIODO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuários.
        /// </summary>
        public static string STR_USUARIOS {
            get {
                return ResourceManager.GetString("STR_USUARIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        public static string STR_VALOR {
            get {
                return ResourceManager.GetString("STR_VALOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor Preço Médio.
        /// </summary>
        public static string STR_VALOR_PRECO_MEDIO {
            get {
                return ResourceManager.GetString("STR_VALOR_PRECO_MEDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor Total Investido.
        /// </summary>
        public static string STR_VALOR_TOTAL_INVESTIDO {
            get {
                return ResourceManager.GetString("STR_VALOR_TOTAL_INVESTIDO", resourceCulture);
            }
        }
    }
}
