//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conectai.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLQueries() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Conectai.Properties.SQLQueries", typeof(SQLQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VBD_BUSCAR_VERSAO_BD.
        /// </summary>
        internal static string BUSCAR_VERSAO_BD {
            get {
                return ResourceManager.GetString("BUSCAR_VERSAO_BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_DEMANDA_ALTERAR.
        /// </summary>
        internal static string DEMANDA_ALTERAR {
            get {
                return ResourceManager.GetString("DEMANDA_ALTERAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_DEMANDA_ASSUMIR.
        /// </summary>
        internal static string DEMANDA_ASSUMIR {
            get {
                return ResourceManager.GetString("DEMANDA_ASSUMIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_DEMANDA_AVALIAR_ATENDIMENTO.
        /// </summary>
        internal static string DEMANDA_AVALIAR_ATENDIMENTO {
            get {
                return ResourceManager.GetString("DEMANDA_AVALIAR_ATENDIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_DEMANDA_BUSCAR_LISTA.
        /// </summary>
        internal static string DEMANDA_BUSCAR_LISTA {
            get {
                return ResourceManager.GetString("DEMANDA_BUSCAR_LISTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_DEMANDA_EXCLUIR.
        /// </summary>
        internal static string DEMANDA_EXCLUIR {
            get {
                return ResourceManager.GetString("DEMANDA_EXCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_DEMANDA_FINALIZAR.
        /// </summary>
        internal static string DEMANDA_FINALIZAR {
            get {
                return ResourceManager.GetString("DEMANDA_FINALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_DEMANDA_INCLUIR.
        /// </summary>
        internal static string DEMANDA_INCLUIR {
            get {
                return ResourceManager.GetString("DEMANDA_INCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_DEMANDA_LER.
        /// </summary>
        internal static string DEMANDA_LER {
            get {
                return ResourceManager.GetString("DEMANDA_LER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_DEMANDA_POR_STATUS_BUSCAR_LISTA.
        /// </summary>
        internal static string DEMANDA_POR_STATUS_BUSCAR_LISTA {
            get {
                return ResourceManager.GetString("DEMANDA_POR_STATUS_BUSCAR_LISTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_DEMANDAS_POR_STATUS_LER_TODOS.
        /// </summary>
        internal static string DEMANDAS_POR_STATUS_LER_TODOS {
            get {
                return ResourceManager.GetString("DEMANDAS_POR_STATUS_LER_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_ESPACO_PUBLICO_ALTERAR.
        /// </summary>
        internal static string ESPACO_PUBLICO_ALTERAR {
            get {
                return ResourceManager.GetString("ESPACO_PUBLICO_ALTERAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_ESPACO_PUBLICO_BUSCAR_LISTA.
        /// </summary>
        internal static string ESPACO_PUBLICO_BUSCAR_LISTA {
            get {
                return ResourceManager.GetString("ESPACO_PUBLICO_BUSCAR_LISTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_ESPACO_PUBLICO_EXCLUIR.
        /// </summary>
        internal static string ESPACO_PUBLICO_EXCLUIR {
            get {
                return ResourceManager.GetString("ESPACO_PUBLICO_EXCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_ESPACO_PUBLICO_INCLUIR.
        /// </summary>
        internal static string ESPACO_PUBLICO_INCLUIR {
            get {
                return ResourceManager.GetString("ESPACO_PUBLICO_INCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_ESPACO_PUBLICO_LER.
        /// </summary>
        internal static string ESPACO_PUBLICO_LER {
            get {
                return ResourceManager.GetString("ESPACO_PUBLICO_LER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_IMPOSTO_USUARIO_ALTERAR.
        /// </summary>
        internal static string IMPOSTO_USUARIO_ALTERAR {
            get {
                return ResourceManager.GetString("IMPOSTO_USUARIO_ALTERAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_IMPOSTO_USUARIO_BUSCAR_LISTA.
        /// </summary>
        internal static string IMPOSTO_USUARIO_BUSCAR_LISTA {
            get {
                return ResourceManager.GetString("IMPOSTO_USUARIO_BUSCAR_LISTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_IMPOSTO_USUARIO_EMITIR_SEGUNDA_VIA.
        /// </summary>
        internal static string IMPOSTO_USUARIO_EMITIR_SEGUNDA_VIA {
            get {
                return ResourceManager.GetString("IMPOSTO_USUARIO_EMITIR_SEGUNDA_VIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_IMPOSTO_USUARIO_EXCLUIR.
        /// </summary>
        internal static string IMPOSTO_USUARIO_EXCLUIR {
            get {
                return ResourceManager.GetString("IMPOSTO_USUARIO_EXCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_IMPOSTO_USUARIO_INCLUIR.
        /// </summary>
        internal static string IMPOSTO_USUARIO_INCLUIR {
            get {
                return ResourceManager.GetString("IMPOSTO_USUARIO_INCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_IMPOSTO_USUARIO_LER.
        /// </summary>
        internal static string IMPOSTO_USUARIO_LER {
            get {
                return ResourceManager.GetString("IMPOSTO_USUARIO_LER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_INDICE_SATISFACAO_LER_TODOS.
        /// </summary>
        internal static string INDICE_SATISFACAO_LER_TODOS {
            get {
                return ResourceManager.GetString("INDICE_SATISFACAO_LER_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_PERFIS_SISTEMA_LER_TODOS.
        /// </summary>
        internal static string PERFIS_SISTEMA_LER_TODOS {
            get {
                return ResourceManager.GetString("PERFIS_SISTEMA_LER_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_STATUS_DEMANDA_LER_TODOS.
        /// </summary>
        internal static string STATUS_DEMANDA_LER_TODOS {
            get {
                return ResourceManager.GetString("STATUS_DEMANDA_LER_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_TIPOS_IMPOSTO_ALTERAR.
        /// </summary>
        internal static string TIPOS_IMPOSTO_ALTERAR {
            get {
                return ResourceManager.GetString("TIPOS_IMPOSTO_ALTERAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_TIPOS_IMPOSTO_BUSCAR_LISTA.
        /// </summary>
        internal static string TIPOS_IMPOSTO_BUSCAR_LISTA {
            get {
                return ResourceManager.GetString("TIPOS_IMPOSTO_BUSCAR_LISTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_TIPOS_IMPOSTO_EXCLUIR.
        /// </summary>
        internal static string TIPOS_IMPOSTO_EXCLUIR {
            get {
                return ResourceManager.GetString("TIPOS_IMPOSTO_EXCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_TIPOS_IMPOSTO_INCLUIR.
        /// </summary>
        internal static string TIPOS_IMPOSTO_INCLUIR {
            get {
                return ResourceManager.GetString("TIPOS_IMPOSTO_INCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_TIPOS_IMPOSTO_LER.
        /// </summary>
        internal static string TIPOS_IMPOSTO_LER {
            get {
                return ResourceManager.GetString("TIPOS_IMPOSTO_LER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_TIPOS_IMPOSTO_LER_TODOS.
        /// </summary>
        internal static string TIPOS_IMPOSTO_LER_TODOS {
            get {
                return ResourceManager.GetString("TIPOS_IMPOSTO_LER_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_TIPOS_SERVICO_LER_TODOS.
        /// </summary>
        internal static string TIPOS_SERVICO_LER_TODOS {
            get {
                return ResourceManager.GetString("TIPOS_SERVICO_LER_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INV_SP_USUARIO_ALTERAR.
        /// </summary>
        internal static string USUARIO_ALTERAR {
            get {
                return ResourceManager.GetString("USUARIO_ALTERAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INV_SP_USUARIO_BUSCAR_LISTA.
        /// </summary>
        internal static string USUARIO_BUSCAR_LISTA {
            get {
                return ResourceManager.GetString("USUARIO_BUSCAR_LISTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INV_SP_USUARIO_EXCLUIR.
        /// </summary>
        internal static string USUARIO_EXCLUIR {
            get {
                return ResourceManager.GetString("USUARIO_EXCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INV_SP_USUARIO_INCLUIR.
        /// </summary>
        internal static string USUARIO_INCLUIR {
            get {
                return ResourceManager.GetString("USUARIO_INCLUIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_USUARIO_LER.
        /// </summary>
        internal static string USUARIO_LER {
            get {
                return ResourceManager.GetString("USUARIO_LER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIS_SP_USUARIO_LER_POR_CODIGO.
        /// </summary>
        internal static string USUARIO_LER_POR_CODIGO {
            get {
                return ResourceManager.GetString("USUARIO_LER_POR_CODIGO", resourceCulture);
            }
        }
    }
}
